# Student Performance Prediction
## Machine Learning- Linear Regression
### Author: Akanksh M
Download Dataset: https://www.kaggle.com/datasets/nikhil7280/student-performance-multiple-linear-regression?resource=download 

In [1]:
# importing neccessary libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
student_dataset = pd.read_csv('Student_Performance.csv')

In [3]:
student_dataset.head(10)

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   
5              3               78                         No            9   
6              7               73                        Yes            5   
7              8               45                        Yes            4   
8              5               77                         No            8   
9              4               89                         No            4   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0  
5                                 6               61.0  
6                                 6               63.0  
7                                 6               42.0  
8                                 2               61.0  
9                                 0               69.0

In [4]:
student_dataset.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [6]:
student_dataset.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [7]:
student_dataset['Extracurricular Activities'] = student_dataset['Extracurricular Activities'].replace({'Yes':1,'No':0}) 

In [8]:
student_dataset.head()

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0              7               99                           1            9   
1              4               82                           0            4   
2              8               51                           1            7   
3              5               52                           1            5   
4              7               75                           0            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [9]:
student_dataset.shape

(10000, 6)

In [30]:
x = student_dataset.drop('Performance Index',axis=1)
y = student_dataset['Performance Index']

In [31]:
x.head(10)

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0              7               99                           1            9   
1              4               82                           0            4   
2              8               51                           1            7   
3              5               52                           1            5   
4              7               75                           0            8   
5              3               78                           0            9   
6              7               73                           1            5   
7              8               45                           1            4   
8              5               77                           0            8   
9              4               89                           0            4   

   Sample Question Papers Practiced  
0                                 1  
1                                 2  
2                                 2  
3                                 2  
4                                 5  
5                                 6  
6                                 6  
7                                 6  
8                                 2  
9                                 0

In [32]:
y.head(10)

0    91.0
1    65.0
2    45.0
3    36.0
4    66.0
5    61.0
6    63.0
7    42.0
8    61.0
9    69.0
Name: Performance Index, dtype: float64

In [36]:
type(y)

pandas.core.series.Series

In [37]:
y = pd.DataFrame(y)

In [39]:
y.head(10)

Performance Index
0               91.0
1               65.0
2               45.0
3               36.0
4               66.0
5               61.0
6               63.0
7               42.0
8               61.0
9               69.0

In [40]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=1)

In [41]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [42]:
model.coef_

array([[2.8549837 , 1.01841307, 0.59923553, 0.48051531, 0.19067341]])

In [43]:
model.intercept_

array([-34.04001955])

In [44]:
model.predict(x_test)

array([[61.17899104],
       [63.79791726],
       [77.75435773],
       ...,
       [65.96254802],
       [37.68353715],
       [61.54117365]])

In [45]:
model.score(x_test,y_test)

0.9883746454897493

In [46]:
y_predicted = pd.DataFrame(model.predict(x_test))

In [49]:
y_test.head(10)

Performance Index
9953               58.0
3850               64.0
4962               75.0
3886               59.0
5437               86.0
8517               34.0
2041               46.0
1989               80.0
1933               41.0
9984               34.0

In [48]:
y_predicted.head(10)

0
0  61.178991
1  63.797917
2  77.754358
3  63.444709
4  86.401232
5  36.633813
6  44.899340
7  80.153366
8  42.474001
9  32.782145

In [51]:
mean_absolute_error = metrics.mean_absolute_error(y_test,y_predicted)
print(f"Mean Absolute Error:{mean_absolute_error}")

Mean Absolute Error:1.6287441676401337


In [52]:
rmse = np.sqrt(mean_absolute_error)
print(f"Root Mean Squared Error: {rmse}")

Root Mean Squared Error: 1.2762226168032496
